[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.build]
commands = [
    "cd client && npm install && npm run build",  # Primero construye el frontend
    "cd ../server && npm install"                # Luego instala dependencias del backend
]

[start]
cmd = "cd server && npm start"
